CREATE TABLE filme(
	idFIlme int primary key,
	titulo varchar(50),
    ano int,
    genero varchar(40),
    diretor varchar(40)
);

INSERT INTO filme VALUES
	(1, 'OS VINGADORES', 2012, 'FICCAO CIENTIFICA', 'JOSS WHEDON'),	
	(2, 'O REI LEÃO', 2019, 'ANIMACAO', 'JON FAVREAU'),
	(3, 'JURASSIC WORLD: O MUNDO DOS DINOSSAUROS', 2015, 'FICCAO CIENTIFICA', 'COLIN TREVORROW'),
	(4, 'HOMEM-ARANHA: SEM VOLTA PARA CASA', 2021, 'FICCAO CIENTIFICA', 'JON WATTS'),
	(5, 'VINGADORES: GUERRA INFINITA', 2018, 'FICCAO CIENTIFICA', 'ANTHONY RUSSO'),
	(6, 'STAR WARS: O DESPERTAR DA FORÇA', 2015, 'FICCAO CIENTIFICA', 'JEFFREY JACOB ABRAMS'),
	(7, 'TITANIC', 1997, 'ROMANCE', 'JAMES CAMERON'),
	(8, 'AVATAR: O 	CAMINHO DA ÁGUA', 2022, 'FICCAO CIENTIFICA', 'JAMES CAMERON'),
	(9, 'VINGADORES: ULTIMATO', 2019, 'FICCAO CIENTIFICA', 'ANTHONY RUSSO'),
	(10, 'AVATAR', 2009, 'FICCAO CIENTIFICA', 'JAMES CAMERON');

SELECT * FROM filme;

SELECT titulo, diretor FROM filme;

SELECT * FROM filme WHERE genero = 'FICCAO CIENTIFICA';

SELECT * FROM filme WHERE diretor = 'JAMES CAMERON';

SELECT * FROM filme ORDER BY titulo;

SELECT * FROM filme ORDER BY diretor DESC;

SELECT * FROM filme
	WHERE titulo LIKE 'O%';

SELECT * FROM filme
	WHERE diretor LIKE '%N';

SELECT * FROM filme
	WHERE genero LIKE '_I%';
    
SELECT * FROM filme
	WHERE titulo LIKE '%A_';

DROP TABLE filme;
