CREATE TABLE professor(
	idProfessor int primary key,
	nome varchar(50),
    especialidade varchar(40),
    dtNasc date
);

INSERT INTO professor VALUES
	(1, 'VIVIAN SILVA', 'BANCO DE DADOS', '1975-06-13'),
	(2, 'MARISE DE BARROS', 'ENGENHARIA DE PRODUÇÃO', '1965-03-21'),
	(3, 'FERNANDO BRANDAO', 'PROCESSAMENTO DE DADOS', '1977-06-10'),
	(4, 'MÔNICA HERRERO', 'ADMINISTRAÇÃO DE EMPRESAS', '1978-03-02'),
	(5, 'KALINE BARREIRA', 'PSICOPEDAGOGIA INSTITUCIONAL', '1976-01-22'),
	(6, 'GERSON SANTOS', 'GERENCIAMENTO DE PROJETOS', '1974-01-11'),
	(7, 'VERA GOULART', 'ADMINISTRAÇÃO DE RECURSOS HUMANOS', '1980-12-18'),
    (8, 'ALESSANDRO GOULART', 'ADMINISTRAÇÃO DE EMPRESAS', '1978-11-10');

SELECT * FROM professor;

SELECT especialidade FROM professor;

SELECT * FROM professor WHERE especialidade = 'ADMINISTRAÇÃO DE RECURSOS HUMANOS';

SELECT * FROM professor ORDER BY nome ASC;

SELECT * FROM professor ORDER BY dtNasc DESC;

SELECT * FROM professor WHERE nome LIKE 'V%';

SELECT * FROM professor WHERE nome LIKE '%T';

SELECT * FROM professor WHERE nome LIKE '_E%';

SELECT * FROM professor WHERE nome LIKE '%R_';

DROP TABLE professor;
